name: Run fumetest_cli

on:
  pull_request:
    branches:
      - main

jobs:
  run-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Print working directory
      run: pwd

    - name: List directory contents
      run: ls -al
        
    - name: Install app dependencies
      run: |
        npm install  # or appropriate install command for your app

    - name: Start web app and determine port
      run: |
        npm start &  # This assumes your app logs the port to console
        sleep 10  # Give it some time to start and log
        port=$(grep -oP 'Server started on port \K\d+' logfile)  # Replace logfile with the actual log file or output
        echo "PORT=$port" >> $GITHUB_ENV
      
    - name: Run fumetest_cli using npx
      run: npx fumetest_cli run --url http://localhost:${{ env.PORT }} --project-id 64de744ee1bc97a5699fe6e8 --timeout 900
